version: "3.4"

networks:
  tekiz-dev:
    driver: bridge

services:
  postgres_image:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "tekizuser"
      POSTGRES_PASSWORD: "tekizuser"
      POSTGRES_DB: "tekizdb"
    networks:
      - tekiz-dev
    restart: always
volumes:
  db_volume:
